### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Dalton-47** [n0mi1k/apk2url#1]
Just an alert, you need to have jadx and apktool installed to run this.
Just run sudo apt-get install apktool
             sudo apt-get install jadx

**Comment by n0mi1k** [comment]
Thank you. I have just updated the readme with these steps.

**Comment by Conexur** [comment]
To install jadx on Ubuntu, I follow this tutorial: https://lindevs.com/install-jadx-on-ubuntu
